name: CI
on:
  push:
    branches:
      - "mamoru*"
      - "develop"
  pull_request:
    branches:
      - "mamoru*"
      - "develop"
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ] # list of os: https://github.com/actions/virtual-environments
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v3
        - run: |
            git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master

        - uses: actions/setup-go@v3
          with:
            go-version: 1.20.x

        - name: Install dependencies on Linux
          if: runner.os == 'Linux'
          run: sudo apt update && sudo apt install build-essential

        - name: Golang-ci install
          if: runner.os == 'Linux'
          run: make lintci-deps

        - uses: actions/cache@v3
          with:
            path: |
              ~/.cache/go-build
              ~/Library/Caches/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: ${{ runner.os }}-go-

        - name: Lint
          if: runner.os == 'Linux'
          run: make lint

        # These tests are flaky
        - name: Test
          run: make test

  integration-tests:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ] # list of os: https://github.com/actions/virtual-environments
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          git submodule update --init --recursive --force
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master

      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install build-essential

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: test-integration
        run: make test-integration
